version: '3.5'

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "ruby lib/app.rb"
    ports:
      - "8080:8080"
    volumes: 
      - "./:/usr/src/app"
